# Generated by Django 5.2.6 on 2025-10-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['title'], 'verbose_name': 'SubTask', 'verbose_name_plural': 'SubTasks'},
        ),
    ]
